apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stem-worker
  namespace: audio2midi
spec:
  selector:
    matchLabels:
      app: stem-worker
  template:
    metadata:
      labels:
        app: stem-worker
    spec:
      nodeSelector:
        tier: worker
      containers:
      - name: stem-worker
        image: rexby117/stem_service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_REGION
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: AWS_REGION } }
          - name: INPUT_BUCKET
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: INPUT_BUCKET } }
          - name: STEM_QUEUE_URL
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: STEM_QUEUE_URL } }
          - name: MIDI_QUEUE_URL
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: MIDI_QUEUE_URL } }
          - name: DYNAMODB_TABLE
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: DYNAMODB_TABLE } }
          - name: PYTHONUNBUFFERED
            value: "1"
        resources:
          limits:
            cpu: "3500m"
            memory: "10Gi"
          requests:
            cpu: "1000m"
            memory: "3Gi"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: midi-worker
  namespace: audio2midi
spec:
  selector:
    matchLabels:
      app: midi-worker
  template:
    metadata:
      labels:
        app: midi-worker
    spec:
      nodeSelector:
        tier: worker
      containers:
      - name: midi-worker
        image: rexby117/midi_service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_REGION
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: AWS_REGION } }
          - name: INPUT_BUCKET
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: INPUT_BUCKET } }
          - name: OUTPUT_BUCKET
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: OUTPUT_BUCKET } }
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: MIDI_QUEUE_URL
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: MIDI_QUEUE_URL } }
          - name: DYNAMODB_TABLE
            valueFrom: { configMapKeyRef: { name: audio2midi-config, key: DYNAMODB_TABLE } }
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
